server:
  port: 80
  ssl:
    enabled: false
    key-alias: tomcat
    key-store: server.keystore
    key-store-type: JKS
    key-store-password: 1qaz@WSX
spring:
  redis:
    host: 47.98.39.157
    password: 1qaz@WSX
    jedis:
      pool:
        max-active: 1